version: '2'

services:

  #------------------------------------------------------------------
  # Volumes
  #------------------------------------------------------------------

  volume_media:
    image: tianon/true
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}
    volumes:
      - ${FRIDAY_LOCATION_TORRENT_DOWNLOADS}:/downloads
      - ${FRIDAY_LOCATION_TORRENT_WATCH}:/watch
      - ${FRIDAY_LOCATION_TVSHOWS}:/tv
      - ${FRIDAY_LOCATION_MOVIES}:/movies
      - ${FRIDAY_ROOT}/config:/config

  #------------------------------------------------------------------
  # Services
  #------------------------------------------------------------------
  transmission:
    image: linuxserver/transmission
    ports:
      - 9091:9091
    expose:
      - 9091
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}
      TZ: ${FRIDAY_TIMEZONE}
    volumes:
      - ${FRIDAY_ROOT}/config/transmission:/config
    volumes_from:
      - volume_media

  couchpotato:
    image: linuxserver/couchpotato
    ports:
      - 5050:5050
    expose:
      - 5050
    links:
      - "transmission:friday_transmission"
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}
      TZ: ${FRIDAY_TIMEZONE}
    volumes:
      - ${FRIDAY_ROOT}/config/couchpotato:/config
    volumes_from:
      - volume_media
    depends_on:
      - transmission
      - jackett

  sickrage:
    image: linuxserver/sickrage
    ports:
      - 8181:8081
    expose:
      - 8181
    links:
      - "transmission:friday_transmission"
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}
      TZ: ${FRIDAY_TIMEZONE}
    volumes:
      - ${FRIDAY_ROOT}/config/sickrage:/config
    volumes_from:
      - volume_media
    depends_on:
      - transmission
      - jackett

  emby:
    image: emby/embyserver
    ports:
      - 8096:8096
      - 8920:8920
    expose:
      - 8096
      - 8920
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}
      TZ: ${FRIDAY_TIMEZONE}
      GIDLIST: 985
    volumes:
      - ${FRIDAY_ROOT}/config/emby:/config
    volumes_from:
      - volume_media

  jackett:
    image: linuxserver/jackett
    ports:
      - 9117:9117
    expose:
      - 9117
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}
      TZ: ${FRIDAY_TIMEZONE}
    volumes:
      - ${FRIDAY_ROOT}/config/jackett:/config
      - ${FRIDAY_LOCATION_TORRENT_WATCH}:/downloads
    volumes_from:
      - volume_media

  organizr:
    image: lsiocommunity/organizr
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}
      TZ: ${FRIDAY_TIMEZONE}
    volumes:
      - ${FRIDAY_ROOT}/config/organizr:/config
    volumes_from:
      - volume_media
    ports:
      - 8000:80
    depends_on:
      - couchpotato

  # mysql:
  #   container_name: friday_mysql
  #   image: linuxserver/mariadb
  #   networks:
  #     - friday
  #   environment:
  #     PGID: ${FRIDAY_CONFIG_PGID}
  #     PUID: ${FRIDAY_CONFIG_PUID}
  #     TZ: ${FRIDAY_TIMEZONE}
  #     MYSQL_ROOT_PASSWORD: ${FRIDAY_DATABASE_PASS}
  #   volumes_from:
  #     - volume_media
  #   volumes:
  #     - ${FRIDAY_ROOT}/config/mysql:/config
  #   ports:
  #     - 3307:3306

        #kodi-headless:
        #container_name: friday_kodi
        #image: linuxserver/kodi-headless
        #networks:
        #friday:
        #aliases:
        #  - ${FRIDAY_NETWORK_KODI_HOSTNAME}
        #environment:
        #PGID: ${FRIDAY_CONFIG_PGID}
        #PUID: ${FRIDAY_CONFIG_PUID}
        #TZ: ${FRIDAY_TIMEZONE}
        #volumes_from:
        #- volume_media
        #volumes:
        #- ${FRIDAY_ROOT}/config/kodi-headless/.kodi:/config/.kodi
        #- ${FRIDAY_LOCATION_TVSHOWS}:${FRIDAY_LOCATION_TVSHOWS}
        #- ${FRIDAY_LOCATION_MOVIES}:${FRIDAY_LOCATION_MOVIES}
        #ports:
        #- 9777:9777/udp
        #- 8585:8080
        #depends_on:
        #- mysql
        #links:
        #- mysql
