version: '2'

services:

  #------------------------------------------------------------------
  # Volumes
  #------------------------------------------------------------------

  volume_media:
    image: tianon/true
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}
    volumes:
      - ${FRIDAY_LOCATION_TORRENT_DOWNLOADS}:/downloads
      - ${FRIDAY_LOCATION_TORRENT_WATCH}:/watch
      - ${FRIDAY_LOCATION_TVSHOWS}:/tv
      - ${FRIDAY_LOCATION_MOVIES}:/movies
      - ${FRIDAY_LOCATION_MUSIC}:/music
      - ${FRIDAY_ROOT}/config:/config

  #------------------------------------------------------------------
  # Services
  #------------------------------------------------------------------
  
  heimdall:
    image: linuxserver/heimdall
    restart: unless-stopped
    hostname: ${FRIDAY_NETWORK_HEIMDALL_HOSTNAME}
    ports:
      - 9876:80
    expose:
      - 9876
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID} 
      TZ: ${FRIDAY_TIMEZONE}         
    volumes:
      - ${FRIDAY_ROOT}/config/heimdall:/config
    volumes_from:
      - volume_media
    networks:
      friday:
        aliases:
          - ${FRIDAY_NETWORK_HEIMDALL_HOSTNAME}
          
  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    hostname: ${FRIDAY_NETWORK_TRANSMISSION_HOSTNAME}
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
      - 51413
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}
      TZ: ${FRIDAY_TIMEZONE}
    volumes:
      - ${FRIDAY_ROOT}/config/transmission:/config
    volumes_from:
      - volume_media
    networks:
      friday:
        aliases:
          - ${FRIDAY_NETWORK_TRANSMISSION_HOSTNAME}

  couchpotato:
    image: linuxserver/couchpotato
    restart: unless-stopped
    hostname: ${FRIDAY_NETWORK_COUCHPOTATO_HOSTNAME}
    ports:
      - 5050:5050
    expose:
      - 5050
    links:
      - transmission
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}
      TZ: ${FRIDAY_TIMEZONE}
    volumes:
      - ${FRIDAY_ROOT}/config/couchpotato:/config
    volumes_from:
      - volume_media
    depends_on:
      - transmission
      # - jackett
    networks:
      friday:
        aliases:
          - ${FRIDAY_NETWORK_COUCHPOTATO_HOSTNAME}

  sickchill:
    image: linuxserver/sickrage
    restart: unless-stopped
    hostname: ${FRIDAY_NETWORK_SICKRAGE_HOSTNAME}
    ports:
      - 8181:8081
    expose:
      - 8181
    links:
      - transmission
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}
      TZ: ${FRIDAY_TIMEZONE}
    volumes:
      - ${FRIDAY_ROOT}/config/sickrage:/config
    volumes_from:
      - volume_media
    depends_on:
      - transmission
      # - jackett
    networks:
      friday:
        aliases:
          - ${FRIDAY_NETWORK_SICKRAGE_HOSTNAME}

  emby:
    image: emby/embyserver
    restart: unless-stopped
    hostname: ${FRIDAY_NETWORK_EMBY_HOSTNAME}
    ports:
      - 8096:8096
      - 8920:8920
    expose:
      - 8096
      - 8920
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}
      TZ: ${FRIDAY_TIMEZONE}
      GIDLIST: 985
    volumes:
      - ${FRIDAY_ROOT}/config/emby:/config
    volumes_from:
      - volume_media
    networks:
      friday:
        aliases:
          - ${FRIDAY_NETWORK_EMBY_HOSTNAME}

  ombi:
    image: linuxserver/ombi
    restart: unless-stopped
    hostname: ${FRIDAY_NETWORK_OMBI_HOSTNAME}
    ports:
      - 3579:3579
    expose:
      - 3579
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}
      TZ: ${FRIDAY_TIMEZONE}      
    volumes:
      - ${FRIDAY_ROOT}/config/ombi:/config
    volumes_from:
      - volume_media
    networks:
      friday:
        aliases:
          - ${FRIDAY_NETWORK_OMBI_HOSTNAME}
  
  lidarr:
    image: linuxserver/lidarr
    restart: unless-stopped
    hostname: ${FRIDAY_NETWORK_LIDARR_HOSTNAME}
    ports:
      - 8686:8686
    expose:
      - 8686
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}          
    volumes:
      - ${FRIDAY_ROOT}/config/lidarr:/config
    volumes_from:
      - volume_media
    networks:
      friday:
        aliases:
          - ${FRIDAY_NETWORK_LIDARR_HOSTNAME}
  nzbget:
    image: linuxserver/nzbget
    restart: unless-stopped
    hostname: ${FRIDAY_NETWORK_NZBGET_HOSTNAME}
    ports:
      - 6789:6789
    expose:
      - 6789
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID} 
      TZ: ${FRIDAY_TIMEZONE}         
    volumes:
      - ${FRIDAY_ROOT}/config/nzbget:/config
    volumes_from:
      - volume_media
    networks:
      friday:
        aliases:
          - ${FRIDAY_NETWORK_NZBGET_HOSTNAME}
  
  hydra:
    image: linuxserver/hydra2
    restart: unless-stopped
    hostname: ${FRIDAY_NETWORK_HYDRA_HOSTNAME}
    ports:
      - 5076:5076
    expose:
      - 5076
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID} 
      TZ: ${FRIDAY_TIMEZONE}         
    volumes:
      - ${FRIDAY_ROOT}/config/hydra:/config
    volumes_from:
      - volume_media
    networks:
      friday:
        aliases:
          - ${FRIDAY_NETWORK_HYDRA_HOSTNAME}    
  
  jackett:
    image: linuxserver/jackett
    ports:
      - 9117:9117
    expose:
      - 9117
    environment:
      PGID: ${FRIDAY_CONFIG_PGID}
      PUID: ${FRIDAY_CONFIG_PUID}
      TZ: ${FRIDAY_TIMEZONE}
    volumes:
      - ${FRIDAY_ROOT}/config/jackett:/config
      - ${FRIDAY_LOCATION_TORRENT_WATCH}:/downloads
    volumes_from:
      - volume_media

  # organizr:
  #   image: lsiocommunity/organizr
  #   environment:
  #     PGID: ${FRIDAY_CONFIG_PGID}
  #     PUID: ${FRIDAY_CONFIG_PUID}
  #     TZ: ${FRIDAY_TIMEZONE}
  #   volumes:
  #     - ${FRIDAY_ROOT}/config/organizr:/config
  #   volumes_from:
  #     - volume_media
  #   ports:
  #     - 8000:80
  #   depends_on:
  #     - couchpotato

  # mysql:
  #   container_name: friday_mysql
  #   image: linuxserver/mariadb
  #   networks:
  #     - friday
  #   environment:
  #     PGID: ${FRIDAY_CONFIG_PGID}
  #     PUID: ${FRIDAY_CONFIG_PUID}
  #     TZ: ${FRIDAY_TIMEZONE}
  #     MYSQL_ROOT_PASSWORD: ${FRIDAY_DATABASE_PASS}
  #   volumes_from:
  #     - volume_media
  #   volumes:
  #     - ${FRIDAY_ROOT}/config/mysql:/config
  #   ports:
  #     - 3307:3306

  # kodi-headless:
  #   container_name: friday_kodi
  #   image: linuxserver/kodi-headless
  #   networks:
  #   friday:
  #   aliases:
  #     - ${FRIDAY_NETWORK_KODI_HOSTNAME}
  #   environment:
  #   PGID: ${FRIDAY_CONFIG_PGID}
  #   PUID: ${FRIDAY_CONFIG_PUID}
  #   TZ: ${FRIDAY_TIMEZONE}
  #   volumes_from:
  #     - volume_media
  #   volumes:
  #     - ${FRIDAY_ROOT}/config/kodi-headless/.kodi:/config/.kodi
  #     - ${FRIDAY_LOCATION_TVSHOWS}:${FRIDAY_LOCATION_TVSHOWS}
  #     - ${FRIDAY_LOCATION_MOVIES}:${FRIDAY_LOCATION_MOVIES}
  #   ports:
  #     - 9777:9777/udp
  #     - 8585:8080
  #   depends_on:
  #     - mysql
  #   links:
  #     - mysql

networks:
  friday:
